name: Build and test main
on:
  push:
    branches: [ main ]

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 9.0.x
    - name: Start containers
      run: docker compose -f "docker-compose-workflow.yaml" up -d --build
    - name: Restore dependencies
      run:  dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Stop containers
      run: docker-compose -f "docker-compose-workflow.yaml" down 