name: Publish nuget
on:
  release:
    types:
      - published

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Test
      run: echo 'version ${{ github.event.release.tag_name }}'
    - name: Restore dependencies
      run:  dotnet restore
    - name: Build
      run: dotnet build -c release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
