name: Publish nuget
on:
  release:
    types:
      - published

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run:  dotnet restore
    - name: Build
      run: dotnet build -c release --no-restore
    - name: Test
      run: dotnet test -c release --no-build --verbosity normal
    - name: Nuget pack
      run: dotnet pack RemoteEntity/RemoteEntity.csproj -p:PackageVersion=${{ github.event.release.tag_name }} -p:PackageID=RemoteEntity -c Release
    - name: Push nuget
      run: dotnet nuget push -k ${{ secrets.NUGET_APIKEY }} "RemoteEntity/bin/Release/*.nupkg" --source nuget.org
